# Generated by Django 3.0.4 on 2020-12-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wanted_cloth_name', models.CharField(max_length=40)),
                ('wanted_brand_nama', models.CharField(max_length=40)),
                ('wanted_season', models.CharField(max_length=7)),
                ('wanted_price', models.PositiveIntegerField()),
                ('priority', models.IntegerField(choices=[(1, 'Priority_1'), (2, 'Priority_2'), (3, 'Priority_3'), (4, 'Priority_4'), (5, 'Priority_5')])),
                ('wanted_images', models.ImageField(upload_to='wanted_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(max_length=40)),
                ('item_info', models.IntegerField(choices=[(1, 'Tops'), (2, 'Pants'), (3, 'Outers'), (4, 'SetUp'), (5, 'Coats'), (6, 'Shoes'), (7, 'Accessories'), (8, 'Belts'), (9, 'Bags'), (10, 'Others')])),
                ('brand_nama', models.CharField(max_length=40)),
                ('season', models.CharField(max_length=7)),
                ('cloth_size', models.CharField(max_length=8)),
                ('material', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField()),
                ('buying_place', models.CharField(max_length=20)),
                ('buying_date', models.DateField(blank=True, null=True, verbose_name='購入日時')),
                ('post_images', models.ImageField(upload_to='post_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
