# Generated by Django 3.0.4 on 2020-12-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='brand_nama',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='wanted',
            old_name='wanted_brand_nama',
            new_name='wanted_brand_name',
        ),
    ]
