# Generated by Django 3.0.4 on 2021-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20201230_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='wanted_images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
