# Generated by Django 3.0.4 on 2021-01-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20210102_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_images',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='wanted_images',
            field=models.ImageField(upload_to='media'),
        ),
    ]
