# Generated by Django 3.0.4 on 2021-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_auto_20210103_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='priority',
            field=models.IntegerField(choices=[(1, '優先度1'), (2, '優先度2'), (3, '優先度3'), (4, '優先度4'), (5, '優先度5')]),
        ),
    ]
