# Generated by Django 3.0.4 on 2021-01-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20210103_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='priority',
            field=models.IntegerField(choices=[(1, '優先度1'), (2, '優先度2'), (3, '優先度3')]),
        ),
    ]
